---
services:
  nginx:
    image: nginx:latest
    container_name: nginx-lab
#    ports:
#      -  "9443:9443"
    #volumes:
    #  - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    #  - ./data:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-lab.rule=Host(`nginx.lenovo.lab`)"
      - "traefik.http.routers.nginx-lab.entrypoints=web"
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend: 
    external: true
