---
volumes: 
  portainer_data:
services:
  portainer:
    container_name: portainer-lab
    ports:
      - "9443:9443"
    image: docker.io/portainer/portainer-ce:latest
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lenovo.lab`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"            
    networks:
      - frontend
networks:
  frontend: 
    external: true 